[package]
name = "makepad-synth-ironfish"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad ironfish example"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "HMVEfWglH6ETM-XrlBqp9bOYnlw="

[dependencies]
makepad-audio-graph = { path = "../../../audio_graph", version = "0.3.0" }

[[bin]]
name = "makepad-example-ironfish"
path = "src/main.rs"