[package]
name = "bender_tessellator"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

[dependencies]
bender_arena = { path = "../arena" }
bender_geometry = { path = "../geometry" }
bender_internal_iter = { path = "../internal_iter" }