[package]
name = "makepad-math"
version = "0.2.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad math"
license = "MIT"

[features] 

[dependencies]
#makepad-microserde = { path = "../microserde", version = "0.1" }