[package]
name = "cargo-makepad"
version = "0.4.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad cargo extension"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "3q9p7hJP7S16AZ2sa6ONkcZPa0w="
metadata.makepad-check-platform = "desktop"

[dependencies]
makepad-miniz = { path = "../../libs/miniz", version = "0.4.0" }
makepad-toml-parser = {path = "../../libs/toml_parser", version = "0.4.0"}
makepad-shell = { path = "../../libs/shell", version = "0.4.0" }
makepad-http = { path = "../../libs/http", version = "0.4.0" } 
makepad-wasm-strip = { path = "../../libs/wasm_strip", version = "0.4.0"}
#espflash = {version = "3.0.0", default-features = false}
[features]
nightly=[]