[package]
name = "widgets"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[features]
mtl = ["render/mtl"]
ogl = ["render/ogl"]
webgl = ["render/webgl"]

[dependencies]
rand = "*"
syn = "*"
proc-macro2 = "*"
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.render]
path="./render"
default-features = false