[package]
name = "makepad-studio"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad studio"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "wYzZ6_rSf-yOavE6qCqFfkBHIaA="

[dependencies]
makepad-widgets = {path="../widgets" , version="0.3.0"}
makepad-code-editor = {path="../code_editor", version="0.1.0"}
makepad-file-protocol = {path="./file_protocol", version="0.3.0"}
makepad-file-server = {path="./file_server", version="0.3.0"}
