[package]
name = "makepad-micro-serde-derive"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "microserde derive"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
