[package]
name = "editor"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }

[dependencies.render]
path="../../render"

[dependencies.widget]
path="../../widget"
