[package]
name = "makepad-example-ironfish"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad ironfish example"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "HMVEfWglH6ETM-XrlBqp9bOYnlw="

[dependencies]
makepad-media = { path = "../../media", version = "0.3.0" }
#makepad-miniz = { path = "../../libs/miniz", version = "0.3.0" }
#makepad-base64 = { path = "../../libs/base64", version = "0.3.0" }

[features]
nightly = ["makepad-media/nightly"]

