[package]
name = "makepad-example-slides"
version = "0.4.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad slide example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "_Cje-i05FmRoF8Bp-FtTHnJ3-fA="

[dependencies]
makepad-code-editor = { path = "../../code_editor", version = "0.4.0" }
makepad-widgets = { path = "../../widgets", version = "0.4.0" }
