[package]
name = "makepad-live-compiler"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
makepad-derive-live = { path = "../derive_live", version = "0.1" }
makepad-id-macros = { path = "id_macros", version = "0.1" }
makepad-math = { path = "../math", version = "0.2" }
makepad-live-tokenizer = { path = "../live_tokenizer", version = "0.1" }
